<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.listeners.resolve_target_entity' shared service.

$this->privates['doctrine.orm.listeners.resolve_target_entity'] = $instance = new \Doctrine\ORM\Tools\ResolveTargetEntityListener();

$instance->addResolveTargetEntity('Odiseo\\BlogBundle\\Model\\ArticleInterface', 'Odiseo\\BlogBundle\\Model\\Article', array());
$instance->addResolveTargetEntity('Odiseo\\BlogBundle\\Model\\ArticleTranslationInterface', 'Odiseo\\BlogBundle\\Model\\ArticleTranslation', array());
$instance->addResolveTargetEntity('Odiseo\\BlogBundle\\Model\\ArticleCategoryInterface', 'Odiseo\\BlogBundle\\Model\\ArticleCategory', array());
$instance->addResolveTargetEntity('Odiseo\\BlogBundle\\Model\\ArticleCategoryTranslationInterface', 'Odiseo\\BlogBundle\\Model\\ArticleCategoryTranslation', array());

return $instance;
