<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.configuration.relation_provider' shared service.

return $this->privates['hateoas.configuration.relation_provider'] = new \Hateoas\Configuration\Provider\RelationProvider(($this->privates['hateoas.configuration.metadata_factory'] ?? $this->load('getHateoas_Configuration_MetadataFactoryService.php')), ($this->privates['hateoas.configuration.provider.resolver.chain'] ?? $this->load('getHateoas_Configuration_Provider_Resolver_ChainService.php')));
