<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.configuration.relations_repository' shared service.

return $this->privates['hateoas.configuration.relations_repository'] = new \Hateoas\Configuration\RelationsRepository(($this->privates['hateoas.configuration.metadata_factory'] ?? $this->load('getHateoas_Configuration_MetadataFactoryService.php')), ($this->privates['hateoas.configuration.relation_provider'] ?? $this->load('getHateoas_Configuration_RelationProviderService.php')));
