<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.configuration.metadata.chain_driver' shared service.

return $this->privates['hateoas.configuration.metadata.chain_driver'] = new \Metadata\Driver\DriverChain(array(0 => ($this->privates['hateoas.configuration.metadata.yaml_driver'] ?? $this->load('getHateoas_Configuration_Metadata_YamlDriverService.php')), 1 => ($this->privates['hateoas.configuration.metadata.xml_driver'] ?? $this->load('getHateoas_Configuration_Metadata_XmlDriverService.php')), 2 => ($this->privates['hateoas.configuration.metadata.extension_driver'] ?? $this->load('getHateoas_Configuration_Metadata_ExtensionDriverService.php'))));
