<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.configuration.metadata.extension_driver' shared service.

return $this->privates['hateoas.configuration.metadata.extension_driver'] = new \Hateoas\Configuration\Metadata\Driver\ExtensionDriver(($this->privates['hateoas.configuration.metadata.annotation_driver'] ?? $this->load('getHateoas_Configuration_Metadata_AnnotationDriverService.php')));
