<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.link_factory' shared service.

return $this->privates['hateoas.link_factory'] = new \Hateoas\Factory\LinkFactory(($this->privates['hateoas.expression.evaluator'] ?? $this->load('getHateoas_Expression_EvaluatorService.php')), ($this->services['hateoas.generator.registry'] ?? $this->load('getHateoas_Generator_RegistryService.php')));
