<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jms_serializer.accessor_strategy.expression' shared service.

return $this->privates['jms_serializer.accessor_strategy.expression'] = new \JMS\Serializer\Accessor\ExpressionAccessorStrategy(($this->privates['jms_serializer.expression_evaluator'] ?? $this->load('getJmsSerializer_ExpressionEvaluatorService.php')), ($this->privates['jms_serializer.accessor_strategy.default'] ?? $this->privates['jms_serializer.accessor_strategy.default'] = new \JMS\Serializer\Accessor\DefaultAccessorStrategy()));
