<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'jms_serializer.json_serialization_visitor' shared service.

$this->services['jms_serializer.json_serialization_visitor'] = $instance = new \JMS\Serializer\JsonSerializationVisitor(($this->privates['jms_serializer.cache_naming_strategy'] ?? $this->load('getJmsSerializer_CacheNamingStrategyService.php')), ($this->privates['jms_serializer.accessor_strategy.expression'] ?? $this->load('getJmsSerializer_AccessorStrategy_ExpressionService.php')));

$instance->setOptions(0);

return $instance;
