<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'odiseo_blog.factory.article_category_translation' shared service.

return $this->services['odiseo_blog.factory.article_category_translation'] = new \Sylius\Component\Resource\Factory\Factory('Odiseo\\BlogBundle\\Model\\ArticleCategoryTranslation');
