<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'odiseo_blog.repository.article_category' shared service.

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));

return $this->services['odiseo_blog.repository.article_category'] = new \Odiseo\BlogBundle\Doctrine\ORM\ArticleCategoryRepository($a, $a->getClassMetadata('Odiseo\\BlogBundle\\Model\\ArticleCategory'));
