<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pagerfanta.view.twitter_bootstrap4' shared service.

return $this->privates['pagerfanta.view.twitter_bootstrap4'] = new \Pagerfanta\View\TwitterBootstrap4View();
