<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pagerfanta.view.twitter_bootstrap3_translated' shared service.

return $this->privates['pagerfanta.view.twitter_bootstrap3_translated'] = new \WhiteOctober\PagerfantaBundle\View\TwitterBootstrap3TranslatedView(($this->privates['pagerfanta.view.twitter_bootstrap3'] ?? $this->privates['pagerfanta.view.twitter_bootstrap3'] = new \Pagerfanta\View\TwitterBootstrap3View()), ($this->services['translator'] ?? $this->getTranslatorService()));
