<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pagerfanta.view.twitter_bootstrap4_translated' shared service.

return $this->privates['pagerfanta.view.twitter_bootstrap4_translated'] = new \WhiteOctober\PagerfantaBundle\View\TwitterBootstrap4TranslatedView(($this->privates['pagerfanta.view.twitter_bootstrap4'] ?? $this->privates['pagerfanta.view.twitter_bootstrap4'] = new \Pagerfanta\View\TwitterBootstrap4View()), ($this->services['translator'] ?? $this->getTranslatorService()));
