<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pagerfanta.view.default_translated' shared service.

return $this->privates['pagerfanta.view.default_translated'] = new \WhiteOctober\PagerfantaBundle\View\DefaultTranslatedView(($this->privates['pagerfanta.view.default'] ?? $this->privates['pagerfanta.view.default'] = new \Pagerfanta\View\DefaultView()), ($this->services['translator'] ?? $this->getTranslatorService()));
