<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pagerfanta.view.twitter_bootstrap_translated' shared service.

return $this->privates['pagerfanta.view.twitter_bootstrap_translated'] = new \WhiteOctober\PagerfantaBundle\View\TwitterBootstrapTranslatedView(($this->privates['pagerfanta.view.twitter_bootstrap'] ?? $this->privates['pagerfanta.view.twitter_bootstrap'] = new \Pagerfanta\View\TwitterBootstrapView()), ($this->services['translator'] ?? $this->getTranslatorService()));
