<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'pagerfanta.view.semantic_ui' shared service.

return $this->privates['pagerfanta.view.semantic_ui'] = new \Pagerfanta\View\SemanticUiView();
