<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.console.command.resource_debug' shared service.

return $this->services['sylius.console.command.resource_debug'] = new \Sylius\Bundle\ResourceBundle\Command\DebugResourceCommand(($this->privates['sylius.resource_registry'] ?? $this->load('getSylius_ResourceRegistryService.php')));
