<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.grid.data_provider' shared service.

return $this->services['sylius.grid.data_provider'] = new \Sylius\Component\Grid\Data\DataProvider(($this->services['sylius.grid.data_source_provider'] ?? $this->load('getSylius_Grid_DataSourceProviderService.php')), ($this->services['sylius.grid.filters_applicator'] ?? $this->load('getSylius_Grid_FiltersApplicatorService.php')), ($this->services['sylius.grid.sorter'] ?? $this->services['sylius.grid.sorter'] = new \Sylius\Component\Grid\Sorting\Sorter()));
