<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.type.default' shared service.

return $this->services['sylius.form.type.default'] = new \Sylius\Bundle\ResourceBundle\Form\Type\DefaultResourceType(($this->privates['sylius.resource_registry'] ?? $this->load('getSylius_ResourceRegistryService.php')), ($this->privates['sylius.registry.form_builder'] ?? $this->load('getSylius_Registry_FormBuilderService.php')));
