<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sm.twig_extension' shared service.

return $this->privates['sm.twig_extension'] = new \SM\Extension\Twig\SMExtension(($this->services['sm.factory'] ?? $this->load('getSm_FactoryService.php')));
