<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.grid_driver.doctrine.orm' shared service.

return $this->services['sylius.grid_driver.doctrine.orm'] = new \Sylius\Bundle\GridBundle\Doctrine\ORM\Driver(($this->services['doctrine'] ?? $this->load('getDoctrineService.php')));
