<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.registry.form_builder' shared service.

$this->privates['sylius.registry.form_builder'] = $instance = new \Sylius\Component\Registry\ServiceRegistry('Sylius\\Bundle\\ResourceBundle\\Form\\Builder\\DefaultFormBuilderInterface', 'form builder');

$instance->register('doctrine/orm', ($this->privates['sylius.form_builder.default'] ?? $this->load('getSylius_FormBuilder_DefaultService.php')));

return $instance;
