<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sm.factory' shared service.

return $this->services['sm.factory'] = new \SM\Factory\Factory(array(), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['sm.callback_factory'] ?? $this->services['sm.callback_factory'] = new \winzou\Bundle\StateMachineBundle\Callback\ContainerAwareCallbackFactory('winzou\\Bundle\\StateMachineBundle\\Callback\\ContainerAwareCallback', $this)));
