<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.grid.provider' shared service.

return $this->services['sylius.grid.provider'] = new \Sylius\Component\Grid\Provider\ArrayGridProvider(($this->services['sylius.grid.array_to_definition_converter'] ?? $this->load('getSylius_Grid_ArrayToDefinitionConverterService.php')), array());
