<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.custom_grid_renderer.twig.inner' shared service.

return $this->privates['sylius.custom_grid_renderer.twig.inner'] = new \Sylius\Bundle\GridBundle\Renderer\TwigGridRenderer(($this->services['twig'] ?? $this->load('getTwigService.php')), ($this->services['sylius.registry.grid_field'] ?? $this->load('getSylius_Registry_GridFieldService.php')), ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), ($this->privates['sylius.form_registry.grid_filter'] ?? $this->load('getSylius_FormRegistry_GridFilterService.php')), 'SyliusGridBundle::_grid.html.twig', array(), array());
