<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.grid.view_factory' shared service.

return $this->services['sylius.grid.view_factory'] = new \Sylius\Component\Grid\View\GridViewFactory(($this->services['sylius.grid.data_provider'] ?? $this->load('getSylius_Grid_DataProviderService.php')));
