<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.custom_grid_renderer.twig' shared service.

return $this->services['sylius.custom_grid_renderer.twig'] = new \Sylius\Bundle\ResourceBundle\Grid\Renderer\TwigGridRenderer(($this->privates['sylius.custom_grid_renderer.twig.inner'] ?? $this->load('getSylius_CustomGridRenderer_Twig_InnerService.php')), ($this->services['twig'] ?? $this->load('getTwigService.php')), ($this->privates['sylius.grid_options_parser'] ?? $this->load('getSylius_GridOptionsParserService.php')), array());
