<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.grid_options_parser' shared service.

return $this->privates['sylius.grid_options_parser'] = new \Sylius\Bundle\ResourceBundle\Grid\Parser\OptionsParser($this, ($this->privates['sylius.expression_language'] ?? $this->privates['sylius.expression_language'] = new \Sylius\Bundle\ResourceBundle\ExpressionLanguage\ExpressionLanguage()), ($this->privates['property_accessor'] ?? $this->load('getPropertyAccessorService.php')));
