<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.registry.grid_driver' shared service.

$this->services['sylius.registry.grid_driver'] = $instance = new \Sylius\Component\Registry\ServiceRegistry('Sylius\\Component\\Grid\\Data\\DriverInterface', 'grid driver');

$instance->register('doctrine/orm', ($this->services['sylius.grid_driver.doctrine.orm'] ?? $this->load('getSylius_GridDriver_Doctrine_OrmService.php')));
$instance->register('doctrine/dbal', ($this->services['sylius.grid_driver.doctrine.dbal'] ?? $this->load('getSylius_GridDriver_Doctrine_DbalService.php')));

return $instance;
