<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.event_subscriber.orm_mapped_super_class' shared service.

return $this->services['sylius.event_subscriber.orm_mapped_super_class'] = new \Sylius\Bundle\ResourceBundle\EventListener\ORMMappedSuperClassSubscriber(($this->privates['sylius.resource_registry'] ?? $this->load('getSylius_ResourceRegistryService.php')));
