<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.random_generator' shared service.

return $this->services['sylius.random_generator'] = new \Sylius\Component\Resource\Generator\RandomnessGenerator();
