<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.templating.helper.bulk_action_grid' shared service.

if ($lazyLoad) {
    return $this->services['sylius.templating.helper.bulk_action_grid'] = $this->createProxy('BulkActionGridHelper_d18a6a1', function () {
        return \BulkActionGridHelper_d18a6a1::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getSylius_Templating_Helper_BulkActionGridService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Sylius\Bundle\GridBundle\Templating\Helper\BulkActionGridHelper(($this->services['sylius.custom_bulk_action_grid_renderer.twig'] ?? $this->load('getSylius_CustomBulkActionGridRenderer_TwigService.php')));
