<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.resource_controller.resource_update_handler' shared service.

return $this->privates['sylius.resource_controller.resource_update_handler'] = new \Sylius\Bundle\ResourceBundle\Controller\ResourceUpdateHandler(($this->privates['sylius.resource_controller.state_machine'] ?? $this->load('getSylius_ResourceController_StateMachineService.php')));
