<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.twig.extension.bulk_action_grid' shared service.

return $this->privates['sylius.twig.extension.bulk_action_grid'] = new \Sylius\Bundle\GridBundle\Twig\BulkActionGridExtension(($this->services['sylius.templating.helper.bulk_action_grid'] ?? $this->load('getSylius_Templating_Helper_BulkActionGridService.php')));
