<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.twig.extension.grid' shared service.

return $this->privates['sylius.twig.extension.grid'] = new \Sylius\Bundle\GridBundle\Twig\GridExtension(($this->services['sylius.templating.helper.grid'] ?? $this->load('getSylius_Templating_Helper_GridService.php')));
