<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.app_variable' shared service.

$this->privates['twig.app_variable'] = $instance = new \Symfony\Bridge\Twig\AppVariable();

$instance->setEnvironment('test');
$instance->setDebug(true);
if ($this->has('request_stack')) {
    $instance->setRequestStack(($this->services['request_stack'] ?? $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));
}

return $instance;
