<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'white_october_pagerfanta.view_factory' shared service.

$this->privates['white_october_pagerfanta.view_factory'] = $instance = new \Pagerfanta\View\ViewFactory();

$instance->add(array('default' => ($this->privates['pagerfanta.view.default'] ?? $this->privates['pagerfanta.view.default'] = new \Pagerfanta\View\DefaultView()), 'default_translated' => ($this->privates['pagerfanta.view.default_translated'] ?? $this->load('getPagerfanta_View_DefaultTranslatedService.php')), 'twitter_bootstrap' => ($this->privates['pagerfanta.view.twitter_bootstrap'] ?? $this->privates['pagerfanta.view.twitter_bootstrap'] = new \Pagerfanta\View\TwitterBootstrapView()), 'twitter_bootstrap3' => ($this->privates['pagerfanta.view.twitter_bootstrap3'] ?? $this->privates['pagerfanta.view.twitter_bootstrap3'] = new \Pagerfanta\View\TwitterBootstrap3View()), 'twitter_bootstrap4' => ($this->privates['pagerfanta.view.twitter_bootstrap4'] ?? $this->privates['pagerfanta.view.twitter_bootstrap4'] = new \Pagerfanta\View\TwitterBootstrap4View()), 'semantic_ui' => ($this->privates['pagerfanta.view.semantic_ui'] ?? $this->privates['pagerfanta.view.semantic_ui'] = new \Pagerfanta\View\SemanticUiView()), 'twitter_bootstrap4_translated' => ($this->privates['pagerfanta.view.twitter_bootstrap4_translated'] ?? $this->load('getPagerfanta_View_TwitterBootstrap4TranslatedService.php')), 'twitter_bootstrap3_translated' => ($this->privates['pagerfanta.view.twitter_bootstrap3_translated'] ?? $this->load('getPagerfanta_View_TwitterBootstrap3TranslatedService.php')), 'twitter_bootstrap_translated' => ($this->privates['pagerfanta.view.twitter_bootstrap_translated'] ?? $this->load('getPagerfanta_View_TwitterBootstrapTranslatedService.php')), 'semantic_ui_translated' => ($this->privates['pagerfanta.view.semantic_ui_translated'] ?? $this->load('getPagerfanta_View_SemanticUiTranslatedService.php'))));

return $instance;
