<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGYv3Vsh\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGYv3Vsh/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGYv3Vsh.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGYv3Vsh\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerGYv3Vsh\appTestDebugProjectContainer(array(
    'container.build_hash' => 'GYv3Vsh',
    'container.build_id' => '71ec4ed8',
    'container.build_time' => 1535468561,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGYv3Vsh');
