<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.dbal.default_connection.event_manager' shared service.

$this->privates['doctrine.dbal.default_connection.event_manager'] = $instance = new \Symfony\Bridge\Doctrine\ContainerAwareEventManager($this);

$instance->addEventSubscriber(($this->services['sylius.event_subscriber.orm_mapped_super_class'] ?? $this->load('getSylius_EventSubscriber_OrmMappedSuperClassService.php')));
$instance->addEventSubscriber(($this->services['sylius.event_subscriber.orm_repository_class'] ?? $this->load('getSylius_EventSubscriber_OrmRepositoryClassService.php')));
$instance->addEventSubscriber(($this->services['sylius.translation.translatable_listener.doctrine.orm'] ?? $this->load('getSylius_Translation_TranslatableListener_Doctrine_OrmService.php')));
$instance->addEventListener(array(0 => 'loadClassMetadata'), ($this->privates['doctrine.orm.listeners.resolve_target_entity'] ?? $this->load('getDoctrine_Orm_Listeners_ResolveTargetEntityService.php')));
$instance->addEventListener(array(0 => 'loadClassMetadata'), ($this->privates['doctrine.orm.default_listeners.attach_entity_listeners'] ?? $this->privates['doctrine.orm.default_listeners.attach_entity_listeners'] = new \Doctrine\ORM\Tools\AttachEntityListenersListener()));

return $instance;
