<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.extension' shared service.

return $this->privates['form.extension'] = new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\ServiceLocator(array('Odiseo\\BlogBundle\\Form\\Type\\ArticleCategoryTranslationType' => function () {
    return ($this->privates['odiseo_blog.form.type.article_category_translation'] ?? $this->privates['odiseo_blog.form.type.article_category_translation'] = new \Odiseo\BlogBundle\Form\Type\ArticleCategoryTranslationType('Odiseo\\BlogBundle\\Model\\ArticleCategoryTranslation', array(0 => 'odiseo')));
}, 'Odiseo\\BlogBundle\\Form\\Type\\ArticleCategoryType' => function () {
    return ($this->privates['odiseo_blog.form.type.article_category'] ?? $this->privates['odiseo_blog.form.type.article_category'] = new \Odiseo\BlogBundle\Form\Type\ArticleCategoryType('Odiseo\\BlogBundle\\Model\\ArticleCategory', array(0 => 'odiseo')));
}, 'Odiseo\\BlogBundle\\Form\\Type\\ArticleTranslationType' => function () {
    return ($this->privates['odiseo_blog.form.type.article_translation'] ?? $this->privates['odiseo_blog.form.type.article_translation'] = new \Odiseo\BlogBundle\Form\Type\ArticleTranslationType('Odiseo\\BlogBundle\\Model\\ArticleTranslation', array(0 => 'odiseo')));
}, 'Odiseo\\BlogBundle\\Form\\Type\\ArticleType' => function () {
    return ($this->privates['odiseo_blog.form.type.article'] ?? $this->privates['odiseo_blog.form.type.article'] = new \Odiseo\BlogBundle\Form\Type\ArticleType('Odiseo\\BlogBundle\\Model\\Article', array(0 => 'odiseo')));
}, 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\BooleanFilterType' => function () {
    return ($this->services['sylius.form.type.grid_filter.boolean'] ?? $this->services['sylius.form.type.grid_filter.boolean'] = new \Sylius\Bundle\GridBundle\Form\Type\Filter\BooleanFilterType());
}, 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\DateFilterType' => function () {
    return ($this->services['sylius.form.type.grid_filter.date'] ?? $this->services['sylius.form.type.grid_filter.date'] = new \Sylius\Bundle\GridBundle\Form\Type\Filter\DateFilterType());
}, 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\EntityFilterType' => function () {
    return ($this->services['sylius.form.type.grid_filter.entity'] ?? $this->services['sylius.form.type.grid_filter.entity'] = new \Sylius\Bundle\GridBundle\Form\Type\Filter\EntityFilterType());
}, 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\ExistsFilterType' => function () {
    return ($this->services['sylius.form.type.grid_filter.exists'] ?? $this->services['sylius.form.type.grid_filter.exists'] = new \Sylius\Bundle\GridBundle\Form\Type\Filter\ExistsFilterType());
}, 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\MoneyFilterType' => function () {
    return ($this->services['sylius.form.type.grid_filter.money'] ?? $this->services['sylius.form.type.grid_filter.money'] = new \Sylius\Bundle\GridBundle\Form\Type\Filter\MoneyFilterType());
}, 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\StringFilterType' => function () {
    return ($this->services['sylius.form.type.grid_filter.string'] ?? $this->services['sylius.form.type.grid_filter.string'] = new \Sylius\Bundle\GridBundle\Form\Type\Filter\StringFilterType());
}, 'Sylius\\Bundle\\ResourceBundle\\Form\\Type\\DefaultResourceType' => function () {
    return ($this->services['sylius.form.type.default'] ?? $this->load('getSylius_Form_Type_DefaultService.php'));
}, 'Sylius\\Bundle\\ResourceBundle\\Form\\Type\\ResourceAutocompleteChoiceType' => function () {
    return ($this->services['sylius.form.type.resource_autocomplete_choice'] ?? $this->load('getSylius_Form_Type_ResourceAutocompleteChoiceService.php'));
}, 'Sylius\\Bundle\\ResourceBundle\\Form\\Type\\ResourceTranslationsType' => function () {
    return ($this->services['sylius.form.type.resource_translations'] ?? $this->load('getSylius_Form_Type_ResourceTranslationsService.php'));
}, 'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => function () {
    return ($this->privates['form.type.entity'] ?? $this->load('getForm_Type_EntityService.php'));
}, 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => function () {
    return ($this->privates['form.type.choice'] ?? $this->load('getForm_Type_ChoiceService.php'));
}, 'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => function () {
    return ($this->privates['form.type.form'] ?? $this->load('getForm_Type_FormService.php'));
})), array('Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.form.http_foundation'] ?? $this->load('getForm_TypeExtension_Form_HttpFoundationService.php'));
    yield 1 => ($this->privates['form.type_extension.form.validator'] ?? $this->load('getForm_TypeExtension_Form_ValidatorService.php'));
    yield 2 => ($this->privates['form.type_extension.upload.validator'] ?? $this->load('getForm_TypeExtension_Upload_ValidatorService.php'));
    yield 3 => ($this->privates['form.type_extension.csrf'] ?? $this->load('getForm_TypeExtension_CsrfService.php'));
}, 4), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.repeated.validator'] ?? $this->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension());
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.submit.validator'] ?? $this->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension());
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\CollectionType' => new RewindableGenerator(function () {
    yield 0 => ($this->services['sylius.form.extension.type.collection'] ?? $this->services['sylius.form.extension.type.collection'] = new \Sylius\Bundle\ResourceBundle\Form\Extension\CollectionTypeExtension());
}, 1)), new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_guesser.validator'] ?? $this->load('getForm_TypeGuesser_ValidatorService.php'));
    yield 1 => ($this->privates['form.type_guesser.doctrine'] ?? $this->load('getForm_TypeGuesser_DoctrineService.php'));
}, 2));
