<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.configuration.metadata_factory' shared service.

$this->privates['hateoas.configuration.metadata_factory'] = $instance = new \Metadata\MetadataFactory(($this->privates['hateoas.configuration.metadata.chain_driver'] ?? $this->load('getHateoas_Configuration_Metadata_ChainDriverService.php')), 'Metadata\\ClassHierarchyMetadata', true);

$instance->setCache(($this->privates['hateoas.configuration.metadata.cache.file_cache'] ?? $this->privates['hateoas.configuration.metadata.cache.file_cache'] = new \Metadata\Cache\FileCache(($this->targetDirs[0].'/hateoas'))));

return $instance;
