<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.twig.link' shared service.

return $this->privates['hateoas.twig.link'] = new \Hateoas\Twig\Extension\LinkExtension(($this->services['hateoas.helper.link'] ?? $this->load('getHateoas_Helper_LinkService.php')));
