<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.configuration.metadata.xml_driver' shared service.

return $this->privates['hateoas.configuration.metadata.xml_driver'] = new \Hateoas\Configuration\Metadata\Driver\XmlDriver(($this->privates['jms_serializer.metadata.file_locator'] ?? $this->privates['jms_serializer.metadata.file_locator'] = new \Metadata\Driver\FileLocator(array())));
