<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'odiseo_blog.form.type.article_category' shared service.

return $this->privates['odiseo_blog.form.type.article_category'] = new \Odiseo\BlogBundle\Form\Type\ArticleCategoryType('Odiseo\\BlogBundle\\Model\\ArticleCategory', array(0 => 'odiseo'));
