<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'odiseo_blog.factory.article' shared service.

return $this->services['odiseo_blog.factory.article'] = new \Sylius\Component\Resource\Factory\TranslatableFactory(new \Sylius\Component\Resource\Factory\Factory('Odiseo\\BlogBundle\\Model\\Article'), ($this->services['sylius.translation_locale_provider.immutable'] ?? $this->services['sylius.translation_locale_provider.immutable'] = new \Sylius\Component\Resource\Translation\Provider\ImmutableTranslationLocaleProvider(array(0 => 'en_US'), 'en_US')));
