<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.grid_driver.doctrine.dbal' shared service.

return $this->services['sylius.grid_driver.doctrine.dbal'] = new \Sylius\Bundle\GridBundle\Doctrine\DBAL\Driver(($this->services['doctrine.dbal.default_connection'] ?? $this->load('getDoctrine_Dbal_DefaultConnectionService.php')));
