<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.type.grid_filter.exists' shared service.

return $this->services['sylius.form.type.grid_filter.exists'] = new \Sylius\Bundle\GridBundle\Form\Type\Filter\ExistsFilterType();
