<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.templating.helper.grid' shared service.

if ($lazyLoad) {
    return $this->services['sylius.templating.helper.grid'] = $this->createProxy('GridHelper_dc9cf99', function () {
        return \GridHelper_dc9cf99::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getSylius_Templating_Helper_GridService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Sylius\Bundle\GridBundle\Templating\Helper\GridHelper(($this->services['sylius.custom_grid_renderer.twig'] ?? $this->load('getSylius_CustomGridRenderer_TwigService.php')));
