<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sm.callback.cascade_transition' shared service.

return $this->services['sm.callback.cascade_transition'] = new \SM\Callback\CascadeTransitionCallback(($this->services['sm.factory'] ?? $this->load('getSm_FactoryService.php')));
