<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.routing.loader.resource' shared service.

return $this->privates['sylius.routing.loader.resource'] = new \Sylius\Bundle\ResourceBundle\Routing\ResourceLoader(($this->privates['sylius.resource_registry'] ?? $this->load('getSylius_ResourceRegistryService.php')), new \Sylius\Bundle\ResourceBundle\Routing\RouteFactory());
