<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.resource_controller.pagerfanta_representation_factory' shared service.

return $this->privates['sylius.resource_controller.pagerfanta_representation_factory'] = new \Hateoas\Representation\Factory\PagerfantaFactory();
