<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.grid_filter.entity' shared service.

return $this->services['sylius.grid_filter.entity'] = new \Sylius\Component\Grid\Filter\EntityFilter();
