<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.grid.array_to_definition_converter' shared service.

return $this->services['sylius.grid.array_to_definition_converter'] = new \Sylius\Component\Grid\Definition\ArrayToDefinitionConverter(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
