<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.form_registry.grid_filter' shared service.

$this->privates['sylius.form_registry.grid_filter'] = $instance = new \Sylius\Bundle\GridBundle\Form\Registry\FormTypeRegistry();

$instance->add('string', 'default', 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\StringFilterType');
$instance->add('boolean', 'default', 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\BooleanFilterType');
$instance->add('date', 'default', 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\DateFilterType');
$instance->add('entity', 'default', 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\EntityFilterType');
$instance->add('money', 'default', 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\MoneyFilterType');
$instance->add('exists', 'default', 'Sylius\\Bundle\\GridBundle\\Form\\Type\\Filter\\ExistsFilterType');

return $instance;
