<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.registry.resource_repository' shared service.

$this->privates['sylius.registry.resource_repository'] = $instance = new \Sylius\Component\Registry\ServiceRegistry('Sylius\\Component\\Resource\\Repository\\RepositoryInterface', 'resource repository');

$instance->register('odiseo_blog.article', ($this->services['odiseo_blog.repository.article'] ?? $this->load('getOdiseoBlog_Repository_ArticleService.php')));
$instance->register('odiseo_blog.article_translation', ($this->services['odiseo_blog.repository.article_translation'] ?? $this->load('getOdiseoBlog_Repository_ArticleTranslationService.php')));
$instance->register('odiseo_blog.article_category', ($this->services['odiseo_blog.repository.article_category'] ?? $this->load('getOdiseoBlog_Repository_ArticleCategoryService.php')));
$instance->register('odiseo_blog.article_category_translation', ($this->services['odiseo_blog.repository.article_category_translation'] ?? $this->load('getOdiseoBlog_Repository_ArticleCategoryTranslationService.php')));

return $instance;
