<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.extension.pagerfanta' shared service.

return $this->privates['twig.extension.pagerfanta'] = new \WhiteOctober\PagerfantaBundle\Twig\PagerfantaExtension('default', ($this->privates['white_october_pagerfanta.view_factory'] ?? $this->load('getWhiteOctoberPagerfanta_ViewFactoryService.php')), ($this->services['router'] ?? $this->getRouterService()), ($this->services['request_stack'] ?? $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));
