<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.runtime_loader' shared service.

return $this->privates['twig.runtime_loader'] = new \Twig\RuntimeLoader\ContainerRuntimeLoader(new \Symfony\Component\DependencyInjection\ServiceLocator(array('JMS\\Serializer\\Twig\\SerializerRuntimeHelper' => function () {
    return ($this->services['jms_serializer.twig_extension.serializer_runtime_helper'] ?? $this->load('getJmsSerializer_TwigExtension_SerializerRuntimeHelperService.php'));
}, 'Symfony\\Bridge\\Twig\\Extension\\CsrfRuntime' => function () {
    return ($this->privates['twig.runtime.security_csrf'] ?? $this->load('getTwig_Runtime_SecurityCsrfService.php'));
}, 'Symfony\\Bridge\\Twig\\Extension\\HttpKernelRuntime' => function () {
    return ($this->privates['twig.runtime.httpkernel'] ?? $this->load('getTwig_Runtime_HttpkernelService.php'));
}, 'Symfony\\Component\\Form\\FormRenderer' => function () {
    return ($this->privates['twig.form.renderer'] ?? $this->load('getTwig_Form_RendererService.php'));
})));
