<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'validator.builder' shared service.

$this->privates['validator.builder'] = $instance = \Symfony\Component\Validator\Validation::createValidatorBuilder();

$instance->setConstraintValidatorFactory(($this->privates['validator.validator_factory'] ?? $this->load('getValidator_ValidatorFactoryService.php')));
$instance->setTranslator(($this->services['translator'] ?? $this->getTranslatorService()));
$instance->setTranslationDomain('validators');
$instance->addXmlMappings(array(0 => ($this->targetDirs[5].'/vendor/symfony/symfony/src/Symfony/Component/Form/Resources/config/validation.xml')));
$instance->addYamlMappings(array(0 => ($this->targetDirs[5].'/src/Resources/config/validation/Article.yml'), 1 => ($this->targetDirs[5].'/src/Resources/config/validation/ArticleCategory.yml'), 2 => ($this->targetDirs[5].'/src/Resources/config/validation/ArticleCategoryTranslation.yml'), 3 => ($this->targetDirs[5].'/src/Resources/config/validation/ArticleTranslation.yml')));
$instance->enableAnnotationMapping(($this->privates['annotations.cached_reader'] ?? $this->load('getAnnotations_CachedReaderService.php')));
$instance->addMethodMapping('loadValidatorMetadata');
$instance->addObjectInitializers(array(0 => ($this->privates['doctrine.orm.validator_initializer'] ?? $this->load('getDoctrine_Orm_ValidatorInitializerService.php'))));

return $instance;
